dist: bionic

addons:
  apt:
    packages:
      - socat

language: cpp

compiler:
  - gcc

before_script:
  - mkdir build_tests
  - cd build_tests
  - cmake ..

script:
  - make -j4
  - ctest -V -R r_unit

after_success:
  - bash <(curl -s https://codecov.io/bash)
